# Generated by Django 3.1.5 on 2021-05-02 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210502_0031'),
        ('users', '0002_auto_20210502_0021'),
    ]

    operations = [
    ]
