#!/bin/bash

if [ "$1" != "dev" ] && [ "$1" != "test" ] && [ "$1" != "prod" ]; then
  echo ""
  echo "First argument must be one of: dev, test, prod"
  echo "For example: '$(dirname "$0")/$(basename "$0") dev'"
  exit 1
fi

cp $(dirname "$0")/app/server_config.$1.py $(dirname "$0")/app/server_config.py
