---
version: "3.8"

services:
  django:
    networks:
      - traefik-global-proxy
    expose:
      - "${PROJECT_PORT_INTERNAL}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${DEV_DOMAIN_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=web"

networks:
  traefik-global-proxy:
    external: true
