# Generated by Django 3.1.4 on 2021-01-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210102_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
