# Generated by Django 4.0.2 on 2022-02-25 20:47

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20210502_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Canada/Mountain'),
        ),
    ]
